services:
  postgres:
    image: postgres:14
    container_name: edu_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eduplatform
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: edu_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'

  backend:
    container_name: edu_backend
    build:
      context: ./backend
    restart: always
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: eduplatform
      JWT_SECRET: supersecretjwtkey123
      JWT_EXPIRES_IN: 3600s
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USER: arystansaidildin@gmail.com
      MAIL_PASS: твой-app-password
      MAIL_FROM: "EduPlatform <arystansaidildin@gmail.com>"

  frontend:
    container_name: edu_frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  edu-net:
    driver: bridge
