export enum NotificationType {
  ASSIGNMENT_ADDED = 'ASSIGNMENT_ADDED',
  ASSIGNMENT_REVIEWED = 'ASSIGNMENT_REVIEWED',
  QUIZ_GRADED = 'QUIZ_GRADED',
  CERTIFICATE_ISSUED = 'CERTIFICATE_ISSUED',
  COURSE_APPLICATION = 'COURSE_APPLICATION',
  COURSE_COMPLETED = 'COURSE_COMPLETED',

}
